name: Collector Job
on:
#  schedule:
#    - cron: '0 10 * * *'
  workflow_dispatch:
    inputs:
      collectForced:
        description: 'Flag to force collection regardless the configuration'
        type: boolean
        default: false
        required: true
      category:
        description: 'News Category to filter out'
        type: string
        required: true
        default: '*'
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
  workflow_call:
    inputs:
      collectForced:
        description: 'Flag to force collection regardless the configuration'
        type: boolean
        default: false
        required: true
      category:
        description: 'News Category to filter out'
        type: string
        required: true
        default: '*'
    outputs:
      status_code:
        description: "Status Code from Climateline API"
        value: ${{jobs.dispatcher.outputs.status_code}}

jobs:

  dispatcher:
    runs-on: ubuntu-latest
    outputs:
      status_code: ${{ steps.dispatcher.outputs.status_code }}
    steps:
      - name: Fetch new articles (dispatcher)
        id: dispatcher
        run: |
          CODE=`curl --write-out '%{http_code}' \
          --silent \
          --output /dev/null \
          --request GET \
          --header 'Authorization: Bearer ${{ secrets.CLIMATELINE_JOB_SECRET }}' \
          --header 'content-type: application/json' \
          --url "https://climateline-processor.vercel.app/api/collector-job?category=$CATEGORY&collect_forced=$PUBLISH_FORCED"`          
          echo "status_code=$CODE" >> $GITHUB_OUTPUT
        if: ${{ github.event_name != 'schedule' }}
        env:
          COLLECT_FORCED: ${{ inputs.collectForced }}
          CATEGORY: ${{ inputs.category }}

#  checker-success:
#    runs-on: ubuntu-latest
#    needs: dispatcher
#    steps:
#      - run: echo success
#        if: ${{ needs.dispatcher.outputs.status_code == '200' }}
#        env:
#          COLLECT_FORCED: ${{ inputs.collectForced }}
#          CATEGORY: ${{ inputs.category }}
#          STATUS: ${{ needs.dispatcher.outputs.status_code }}
#
#  checker-no-content:
#    runs-on: ubuntu-latest
#    needs: dispatcher
#    steps:
#      - run: echo no-content
#        if: ${{ needs.dispatcher.outputs.status_code == '204' }}
#        env:
#          COLLECT_FORCED: ${{ inputs.collectForced }}
#          CATEGORY: ${{ inputs.category }}
#          STATUS: ${{ needs.dispatcher.outputs.status_code }}

  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch new articles (schedule)
        run: |
          CODE=`curl --write-out '%{http_code}' \
          --silent \
          --output /dev/null \
          --request GET \
          --header 'Authorization: Bearer ${{ secrets.CLIMATELINE_JOB_SECRET }}' \
          --header 'content-type: application/json' \
          --url "https://climateline-processor.vercel.app/api/collector-job?category=$CATEGORY&collect_forced=$COLLECT_FORCED"`                    
          if [ $CODE != "200" ]; then 
            exit 1
          fi
#        if: ${{ github.event_name == 'schedule' }}
        if: github.event.schedule == '0 22 * * *'
        env:
          COLLECT_FORCED: false
          CATEGORY: climate
