name: Collector Job
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
    inputs:
      collectForced:
        description: 'Flag to force collection regardless the configuration'
        type: collect_forced
        default: false
        required: true
      category:
        description: 'News Category to filter out'
        type: category
        required: true
        default: '*'
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  dispatcher1:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch new articles (dispatcher)
        id: dispatcher
        run: |
          CODE=`curl --write-out '%{http_code}' \
          --silent \
          --output /dev/null \
          --request GET \
          --header 'Authorization: Bearer ${{ secrets.CLIMATELINE_JOB_SECRET }}' \
          --header 'content-type: application/json' \
          --url "https://climateline-processor.vercel.app/api/collector-job?category=$CATEGORY&collect_forced=$COLLECT_FORCED"`                              
          if [ $CODE != "200" ]; then 
            exit 1
          fi
        if: ${{ github.event_name != 'schedule' }}
        env:
          COLLECT_FORCED: ${{ inputs.collectForced }}
          CATEGORY: ${{ inputs.category }}

  dispatcher2:
    runs-on: ubuntu-latest
    needs: dispatcher1
    steps:
      - name: Fetch new articles (dispatcher)
        id: dispatcher
        run: echo $GITHUB_OUTPUT
        if: ${{ github.event_name != 'schedule' }}
        env:
          COLLECT_FORCED: ${{ inputs.collectForced }}
          CATEGORY: ${{ inputs.category }}

  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch new articles (schedule)
        run: |
          CODE=`curl --write-out '%{http_code}' \
          --silent \
          --output /dev/null \
          --request GET \
          --header 'Authorization: Bearer ${{ secrets.CLIMATELINE_JOB_SECRET }}' \
          --header 'content-type: application/json' \
          --url "https://climateline-processor.vercel.app/api/collector-job?category=$CATEGORY&collect_forced=$COLLECT_FORCED"`                    
          if [ $CODE != "200" ]; then 
            exit 1
          fi
        if: ${{ github.event_name == 'schedule' }}
        env:
          COLLECT_FORCED: false
          CATEGORY: climate
