name: Collector Dispatcher

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch new articles
        run: |
          curl --request GET \
          --url 'https://climateline-processor.vercel.app/api/collector-job' \
          --header 'Authorization: Bearer ${{ secrets.CLIMATELINE_JOB_SECRET }}'
