name: Collector Dispatcher

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch new articles
        run: |
          curl --request GET \
          --url 'https://climateline-processor.vercel.app/api/job-collector' \
          --header 'Authorization: Bearer ${{ secrets.CLIMATELINE_JOB_SECRET }}'
