name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
    inputs:
      collectForced:
        description: 'Flag to force collection regardless the configuration'
        type: collect_forced
        default: false
        required: true
      category:
        description: 'News Category to filter out'
        type: category
        default: '*'
        required: true
      environment:
        description: 'Environment to run tests against'
        type: environment
        default: 'production'
        required: false

jobs:
  job1:
    uses: margostino/climateline-processor/.github/workflows/collector-job.yml@master

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.publisherResult }}