name: Call Collector Workflow

on:
  workflow_dispatch:
    inputs:
      collectForced:
        description: 'Flag to force collection regardless the configuration'
        type: boolean
        default: false
        required: true
      category:
        description: 'News Category to filter out'
        type: string
        default: '*'
        required: true
      environment:
        description: 'Environment to run tests against'
        type: environment
        default: 'production'
        required: false

jobs:
  caller:
    uses: margostino/climateline-processor/.github/workflows/collector-job.yml@master
    with:
      collectForced: ${{ inputs.collectForced }}
      category: ${{ inputs.category }}
    secrets: inherit

  checker:
    runs-on: ubuntu-latest
    needs: caller
    steps:
      - run: echo sarlanfa ${{ needs.caller.outputs.status_code }}