name: Collector Checker Job
on:
  workflow_call:
    inputs:
      climateresult:
        required: false
        type: string

jobs:

  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Show result
        run: echo $RESULTS
        env:
          RESULTS: ${{ inputs.climateresult }}