name: Fetcher Job
on:
  schedule:
    - cron: '* 18 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch new articles
        run: |
          curl --request GET \
          --url 'https://climateline-processor.vercel.app/api/job' \
          --header 'Authorization: Bearer ${{ secrets.CLIMATELINE_JOB_SECRET }}'
