name: Publisher Job (air)
on:
  schedule:
    - cron: '15 11 * * *'
    - cron: '15 17 * * *'
    - cron: '15 23 * * *'    
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      publishForced:
        description: 'Flag to force publisher regardless the configuration'
        type: boolean
        default: true
        required: true
      category:
        description: 'News Category to filter out'
        type: string
        required: true
        default: 'air'
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  publisher:
    runs-on: ubuntu-latest
    outputs:
      statusCode: ${{ steps.dispatcher.outputs.statusCode }}
    steps:
      - name: Publish new articles (schedule)
        run: |
          CODE=`curl --write-out '%{http_code}' \
          --silent \
          --output /dev/null \
          --request GET \
          --header 'Authorization: Bearer ${{ secrets.CLIMATELINE_JOB_SECRET }}' \
          --header 'content-type: application/json' \
          --url "https://climateline-processor.vercel.app/api/publisher-job?category=$CATEGORY&publish_forced=$PUBLISH_FORCED"`          
          if [ $CODE != "200" ]; then 
            exit 1
          fi
        if: ${{ github.event_name == 'schedule' }}
        env:
          PUBLISH_FORCED: true
          CATEGORY: air
      - name: Publish new articles (dispatch)
        id: dispatcher
        run: |
          CODE=`curl --write-out '%{http_code}' \
          --silent \
          --output /dev/null \
          --request GET \
          --header 'Authorization: Bearer ${{ secrets.CLIMATELINE_JOB_SECRET }}' \
          --header 'content-type: application/json' \
          --url "https://climateline-processor.vercel.app/api/publisher-job?category=$CATEGORY&publish_forced=$PUBLISH_FORCED"`          
          echo "statusCode=$CODE" >> $GITHUB_OUTPUT
        if: ${{ github.event_name != 'schedule' }}
        env:
          PUBLISH_FORCED: ${{ inputs.publishForced }}
          CATEGORY: ${{ inputs.category }}
      - name: debugging-steps
        run: echo debugging
        if: ${{ steps.dispatcher.outputs.status_code == '204' }}

  checker-debugger:
    runs-on: ubuntu-latest
    needs: publisher
    if: ${{ needs.dispatcher.outputs.status_code == '404' }}
    steps:
      - run: echo success
        if: ${{ needs.dispatcher.outputs.status_code == '404' }}
        env:
          COLLECT_FORCED: ${{ inputs.collectForced }}
          CATEGORY: ${{ inputs.category }}
          STATUS: ${{ needs.dispatcher.outputs.status_code }}

  checker-no-content:
    uses: margostino/climateline-processor/.github/workflows/publisher-no-content-checker-job.yml@master
    needs: publisher
    if: ${{ needs.publisher.outputs.statusCode == '204' }}
    with:
      statusCode: ${{ needs.publisher.outputs.statusCode }}
    secrets: inherit

  checker-success:
    uses: margostino/climateline-processor/.github/workflows/publisher-success-checker-job.yml@master
    needs: publisher
    if: ${{ needs.publisher.outputs.statusCode == '200' }}
    with:
      statusCode: ${{ needs.publisher.outputs.statusCode }}
    secrets: inherit