name: Publisher Job
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
    inputs:
      publishForced:
        description: 'Flag to force publisher regardless the configuration'
        type: publish_forced
        required: true
        default: false
      category:
        description: 'News Category to filter out'
        type: category
        required: true
        default: '*'
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
        
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch new articles
        run: |
          curl --request GET \
          --url 'https://climateline-processor.vercel.app/api/publisher-job?publish_forced=false' \
          --header 'Authorization: Bearer ${{ secrets.CLIMATELINE_JOB_SECRET }}'
