name: Publisher Job (heatwave)
on:
  schedule:
    - cron: '0 20 * * *'
        
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:

      - name: Publish new articles
        run: |
          CODE=`curl --write-out '%{http_code}' \
          --silent \
          --output /dev/null \
          --request GET \
          --header 'Authorization: Bearer ${{ secrets.CLIMATELINE_JOB_SECRET }}' \
          --header 'content-type: application/json' \
          --url "https://climateline-processor.vercel.app/api/publisher-job?category=$CATEGORY&publish_forced=$PUBLISH_FORCED"`          
          if [ $CODE != "200" ]; then 
            exit 1
          fi
        env:
          PUBLISH_FORCED: false
          CATEGORY: heatwave

